### ISSUE TITLE
Not working on Heroku-18 Stack

### ISSUE THREAD

**Issue by mayordwells** [rposborne/wkhtmltopdf-heroku#38] opened 2018-06-08 22:00 UTC
Please when can you help get this to work on Heroku-18 stack?
When I checked my stack, it showed this:
ndt-nordvest (master) $ heroku stack
=== ⬢ ndt-nordvest Available Stacks
  cedar-14
  container
  heroku-16
* heroku-18

Thank you.

**Comment by rposborne** [comment] 2018-06-11 01:46
This is a duplicate of #37 closing in favor of that issue

**Closed by rposborne** 2018-06-11 01:46 UTC
